src/entryProject/Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using entryProject.Models.DbModels;
using Microsoft.AspNetCore.Http;

namespace entryProject.Controllers
{
    public class CardsController : Controller
    {

        // NOTICE:
        /*
         * Ive create a "traditional" view oriented controller for this purpose because it goes nicely with ajax for partial views refresh that i used on the FE.
         * If i would be using angular I would have created an API style controller.
         * 
         * */

        aspnet_entryProject_1ec08db8_47b0_4fae_82d7_4da8440d3aa6Context dataSource = new aspnet_entryProject_1ec08db8_47b0_4fae_82d7_4da8440d3aa6Context();
        [Authorize]
        public IActionResult Index()
        {
            return View(dataSource.CsCard);
        }

        [Authorize]
        public async Task<IActionResult> createVisitorsCard([FromForm]CsCard card)
        {
            if(ModelState.IsValid)
            {
                if (card.Name != null && card.Surname != null)
                {
                    if (dataSource.CsCard.FirstOrDefault(x => x.Name == card.Name && x.Surname == card.Surname && x.Active == true) == null)
                    {
                        dataSource.CsCard.Add(card);
                        try
                        {
                            await dataSource.SaveChangesAsync();
                        }
                        catch (Exception)
                        {
                            return StatusCode(StatusCodes.Status500InternalServerError, "Unable to save data. Contact admin!");
                        }
                    }
                    else
                        return StatusCode(StatusCodes.Status409Conflict, "Visitor with this name already exists");
                }
                else
                    return StatusCode(StatusCodes.Status400BadRequest, "Name and surname are required!");
            }

            return PartialView("CardsPartial", dataSource.CsCard);
        }

        [Authorize]
        public async Task<IActionResult> deleteVisitorsCard(long id)
        {
            var card = dataSource.CsCard.FirstOrDefault(x => x.IdCard == id);
            if(card!=null)
                if(card.Active)
                    return StatusCode(StatusCodes.Status400BadRequest, "Visitor is checked-in!"); 
            else
                {
                    dataSource.Remove(dataSource.CsCard.Where(x => x.IdCard == id).First());
                    await dataSource.SaveChangesAsync();
                }
            else
            {
                return StatusCode(StatusCodes.Status400BadRequest, "No such card ID!");
            }

            return PartialView("CardsPartial", dataSource.CsCard);
        }

        [Authorize]
        public async Task<IActionResult> deactivate(long id)
        {
            var card = dataSource.CsCard.FirstOrDefault(x => x.IdCard == id);
            if (card != null)
                if (!card.Active)
                    return StatusCode(StatusCodes.Status400BadRequest, "Visitor is already inactive");
                else
                {
                    dataSource.CsCard.Where(x => x.IdCard == id).First().Active = false;
                    await dataSource.SaveChangesAsync();
                }
            else
            {
                return StatusCode(StatusCodes.Status400BadRequest, "No such card ID!");
            }

            return PartialView("CardsPartial", dataSource.CsCard);
        }
        [Authorize]
        public async Task<IActionResult> activate(long id)
        {
            var card = dataSource.CsCard.FirstOrDefault(x => x.IdCard == id);
            if (card != null)
                if (card.Active)
                    return StatusCode(StatusCodes.Status400BadRequest, "Visitor is already active");
                else
                {
                    dataSource.CsCard.Where(x => x.IdCard == id).First().Active = true;
                    await dataSource.SaveChangesAsync();
                }
            else
            {
                return StatusCode(StatusCodes.Status400BadRequest, "No such card ID!");
            }

            return PartialView("CardsPartial", dataSource.CsCard);
        }

       
    }
}

src/entryProject/Controllers/EntriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using entryProject.Models.DbModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace entryProject.Controllers
{
    public class EntriesController : Controller
    {
        aspnet_entryProject_1ec08db8_47b0_4fae_82d7_4da8440d3aa6Context dataSource = new aspnet_entryProject_1ec08db8_47b0_4fae_82d7_4da8440d3aa6Context();
        public IActionResult Index()
        {
            var outputModel = dataSource.TbEntries.Include(x => x.IdCardNavigation)
                .Include(x => x.IdIssuerNavigation);
            return View(outputModel);
        }

        [Authorize]
        public async Task<IActionResult> checkIn(long id)
        {
            var card = dataSource.CsCard.FirstOrDefault(x => x.IdCard == id);
            if (card != null)
                if (card.Active)
                {
                    var entryList = dataSource.TbEntries.Where(x => x.IdCard == id).OrderByDescending(x=>x.Datetime).FirstOrDefault();
                    if (entryList != null)
                    {
                        if(entryList.IsCheckedIn)
                            return StatusCode(StatusCodes.Status400BadRequest, "Visitor is already checked-in!");
                        else
                            try
                            {
                                await checkInCard(id);
                            }
                            catch (Exception)
                            {
                                return StatusCode(StatusCodes.Status400BadRequest, "Error saving changes! Contact admin!");
                            }
                    }
                    else
                        try
                        {
                            await checkInCard(id);
                        }
                        catch (Exception)
                        {
                            return StatusCode(StatusCodes.Status400BadRequest, "Error saving changes! Contact admin!");
                        }
                }
                else
                    return StatusCode(StatusCodes.Status400BadRequest, "This card is inactive!");
            else
                return StatusCode(StatusCodes.Status400BadRequest, "No such card ID!");

            var outputModel = dataSource.TbEntries.Include(x => x.IdCardNavigation)
               .Include(x => x.IdIssuerNavigation);

            return PartialView("EntriesPartial", outputModel);
        }

        [Authorize]
        public async Task<IActionResult> checkOut(long id)
        {
            var card = dataSource.CsCard.FirstOrDefault(x => x.IdCard == id);
            if (card != null)
                if (card.Active)
                {
                    var entryList = dataSource.TbEntries.Where(x => x.IdCard == id).LastOrDefault();
                    if (entryList != null)
                    {
                        if (!entryList.IsCheckedIn)
                            return StatusCode(StatusCodes.Status400BadRequest, "Visitor is already checked-out!");
                        else
                        {
                            try
                            {
                                await checkOutCard(id);
                            }
                            catch (Exception)
                            {
                                return StatusCode(StatusCodes.Status400BadRequest, "Error saving changes! Contact admin!");
                            }
                        }
                    }
                    else
                        try
                        {
                            await checkOutCard(id);
                        }
                        catch (Exception)
                        {
                            return StatusCode(StatusCodes.Status400BadRequest, "Error saving changes! Contact admin!");
                        }
                }
                else
                    return StatusCode(StatusCodes.Status400BadRequest, "This card is inactive!");
            else
                return StatusCode(StatusCodes.Status400BadRequest, "No such card ID!");

            var outputModel = dataSource.TbEntries.Include(x => x.IdCardNavigation)
               .Include(x => x.IdIssuerNavigation);

            return PartialView("EntriesPartial", outputModel);
        }

        private async Task checkInCard(long id)
        {
            try
            {
                dataSource.TbEntries.Add(new TbEntries
                {
                    IdCard = id,
                    IdIssuer = dataSource.AspNetUsers.First(x => x.UserName == User.Identity.Name).Id,
                    IsCheckedIn = true,
                    Datetime = DateTime.Now
                });

                await dataSource.SaveChangesAsync();
            }
            catch (Exception)
            {
                throw new Exception();
            }
        }

        private async Task checkOutCard(long id)
        {
            try
            {
                dataSource.TbEntries.Add(new TbEntries
                {
                    IdCard = id,
                    IdIssuer = dataSource.AspNetUsers.First(x => x.UserName == User.Identity.Name).Id,
                    IsCheckedIn = false,
                    Datetime = DateTime.Now
                });
                await dataSource.SaveChangesAsync();
            }
            catch (Exception)
            {
                throw new Exception();
            }
        }
    }

}

src/entryProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - entryProject</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/jquery-growl/stylesheets/jquery.growl.css" asp-append-version="true" />
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/jquery-growl/stylesheets/jquery.growl.css" asp-append-version="true" />
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css" />
        
    </environment>
</head>
<body>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery-growl/javascripts/jquery.growl.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        
        
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
        
    </environment>

    @RenderSection("scripts", required: false)
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MintIt-entry</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Entries" asp-action="Index">Entries</a></li>
                    <li><a asp-area="" asp-controller="Cards" asp-action="Index">Cards</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="padding:30px">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - MinIt-Entry</p>
        </footer>
    </div>
</body>
</html>